Repository pingcap-incubator/tiup-cluster, pull requests merged in 2020-05, with the labels that each got.

#357 Add a testst about default data dir
  pkg/meta/topology_test.go
  tests/test_cmd.sh
  tests/topo/full.yaml
Labels: testing

#361 check: ignore comments when checking selinux config
  pkg/operation/check.go
Labels: bugfix

#362 scale-out: report error if the 'import=true' is set for new instance
  cmd/cluster/command/deploy.go
  cmd/cluster/command/scale_out.go
Labels: enhancement

#369 cmd: add --wait-timeout to specify timeout for wait operations
  cmd/cluster/command/check.go
  cmd/cluster/command/deploy.go
  cmd/cluster/command/destroy.go
  cmd/cluster/command/display.go
  cmd/cluster/command/exec.go
  cmd/cluster/command/import.go
  cmd/cluster/command/patch.go
  cmd/cluster/command/reload.go
  cmd/cluster/command/restart.go
  cmd/cluster/command/root.go
  cmd/cluster/command/scale_in.go
  cmd/cluster/command/scale_out.go
  cmd/cluster/command/start.go
  cmd/cluster/command/stop.go
  cmd/cluster/command/upgrade.go
  cmd/dm/command/deploy.go
  cmd/dm/command/destroy.go
  cmd/dm/command/root.go
  cmd/dm/command/start.go
  cmd/dm/command/stop.go
  pkg/meta/logic.go
  pkg/meta/logic_dm.go
  pkg/module/wait_for.go
  pkg/operation/action.go
  pkg/operation/destroy.go
  pkg/operation/operation.go
  pkg/operation/scale_in.go
  pkg/operation/upgrade.go
  pkg/task/action.go
Labels: enhancement

#363 Add support for hybrid os/arch
  cmd/cluster/command/check.go
  cmd/cluster/command/deploy.go
  cmd/cluster/command/display.go
  cmd/cluster/command/reload.go
  cmd/cluster/command/scale_in.go
  cmd/cluster/command/scale_out.go
  cmd/cluster/command/upgrade.go
  cmd/dm/command/deploy.go
  pkg/cliutil/prepare/prepare.go
  pkg/cliutil/tui.go
  pkg/meta/logic.go
  pkg/meta/logic_dm.go
  pkg/meta/topology.go
  pkg/meta/topology_dm.go
  pkg/meta/topology_dm_test.go
  pkg/meta/topology_test.go
  pkg/task/builder.go
  pkg/task/copy_component.go
  pkg/task/download.go
  pkg/task/env_init.go
Labels: enhancement

#371 import: add support of ssh port defined in ansible.cfg
  cmd/cluster/command/import.go
  go.mod
  go.sum
  pkg/ansible/inventory.go
Labels: enhancement

#353 import: add simple unit test cases for inventory parsing
  pkg/ansible/dirs.go
  pkg/ansible/import.go
  pkg/ansible/import_test.go
  pkg/ansible/inventory.go
  pkg/ansible/test-data/ansible.cfg
  pkg/ansible/test-data/group_vars/alertmanager_servers.yml
  pkg/ansible/test-data/group_vars/all.yml
  pkg/ansible/test-data/group_vars/drainer_servers.yml
  pkg/ansible/test-data/group_vars/grafana_servers.yml
  pkg/ansible/test-data/group_vars/importer_server.yml
  pkg/ansible/test-data/group_vars/lightning_server.yml
  pkg/ansible/test-data/group_vars/monitored_servers.yml
  pkg/ansible/test-data/group_vars/monitoring_servers.yml
  pkg/ansible/test-data/group_vars/pd_servers.yml
  pkg/ansible/test-data/group_vars/pump_servers.yml
  pkg/ansible/test-data/group_vars/tidb_servers.yml
  pkg/ansible/test-data/group_vars/tiflash_servers.yml
  pkg/ansible/test-data/group_vars/tikv_servers.yml
  pkg/ansible/test-data/inventory.ini
  pkg/ansible/test-data/meta.yaml
  pkg/meta/topology.go
  pkg/meta/topology_test.go
Labels: testing

#390 meta: store imported configs in a dedicated path
  cmd/cluster/command/deploy.go
  cmd/cluster/command/edit_config.go
  cmd/cluster/command/reload.go
  cmd/cluster/command/root.go
  cmd/cluster/command/scale_in.go
  cmd/cluster/command/scale_out.go
  cmd/cluster/command/upgrade.go
  cmd/dm/command/deploy.go
  pkg/ansible/config.go
  pkg/meta/drainer.go
  pkg/meta/logic.go
  pkg/meta/logic_dm.go
  pkg/meta/pump.go
  pkg/meta/server_config.go
  pkg/meta/topology_test.go
  pkg/task/backup_component.go
  pkg/task/init_config.go
  pkg/task/scale_config.go
  pkg/utils/utils.go
Labels: bugfix

#409 task: fix backup error on imported cluster
  pkg/task/backup_component.go
Labels: bugfix

#415 tests: add root.json to CI
  tests/root.json
  tests/run.sh
  tests/test_upgrade.sh
Labels: testing

#405 check: add an arg to skip conflict checking with exist clusters
  cmd/cluster/command/check.go
  go.mod
  go.sum
Labels: enhancement
