Repository pingcap-incubator/tiup-cluster, pull requests merged in 2020-04, with the labels that each got.

#162 restart error after restart cluster imported from tidb-ansible
  cmd/deploy.go
  cmd/scale_in.go
  cmd/scale_out.go
Labels: bug

#198 import: support custom inventory file name
  cmd/import.go
  pkg/ansible/import.go
  pkg/ansible/inventory.go
Labels: enhancement

#238 set the reload `tranfer-time` options
  cmd/edit_config.go
  cmd/reload.go
Labels: bug

#239 remove the --start flag from deply subcommand
  cmd/deploy.go
Labels: enhancement

#242 Fix bug when default ansible import variable is not set
  cmd/import.go
Labels: bug

#241 import: read variables of host in inventory for monitoring components
  pkg/ansible/inventory.go
Labels: bug

#254 Add ci workflow and static check
  .github/workflows/ci.yaml
  Makefile
  README.md
  pkg/ansible/inventory.go
  pkg/api/binlog.go
  tools/check/check-tidy.sh
  tools/check/go.mod
  tools/check/go.sum
  tools/check/revive.toml
Labels: PTAL

#252 Add tiflash and monitor in test script
  tests/test_cmd.sh
  tests/topo/full.yaml
Labels: PTAL

#258 import: handle ansible_port in inventory properly
  go.mod
  pkg/ansible/inventory.go
Labels: bug

#259 let tiflash proxy use DataDir instead of DeployDir
  pkg/meta/logic.go
Labels: PTAL

#267 disable tiup download progress bar
  go.mod
  go.sum
  pkg/logger/debug.go
  pkg/task/download.go
  tests/script/pull_log.sh
Labels: enhancement

#274 restart prometheus when scale-out
  cmd/scale_out.go
Labels: bugfix

#271 import: refine the import process
  cmd/deploy.go
  cmd/destroy.go
  cmd/edit_config.go
  cmd/import.go
  cmd/root.go
  cmd/scale_in.go
  cmd/scale_out.go
  pkg/ansible/import.go
  pkg/ansible/inventory.go
Labels: enhancement

#277 cmd/exec: print output of command
  cmd/exec.go
  pkg/task/shell.go
  pkg/task/task.go
Labels: enhancement

#275 Add test command to integration test
  cmd/root.go
  cmd/test.go
  go.mod
  go.sum
  tests/test_cmd.sh
Labels: PTAL

#268 add force opt for scale in
  cmd/scale_in.go
  pkg/operation/scale_in.go
Labels: PTAL

#280 meta: merge imported config of pump and drainer
  pkg/meta/drainer.go
  pkg/meta/pump.go
Labels: bugfix

#297 Fix cluster name in grafana
  templates/scripts/run_grafana.sh.tpl
Labels: bug

#310 check: add numactl command check
  cmd/cluster/command/check.go
  go.mod
  go.sum
  pkg/operation/check.go
  pkg/task/check.go
Labels: bug, enhancement

#311 check: add check to find if port in topology already been listened by…
  cmd/cluster/command/check.go
  go.mod
  go.sum
  pkg/operation/check.go
  pkg/task/check.go
  pkg/task/task.go
Labels: enhancement

#327 Bugfix: scale grafana component failed
  pkg/meta/logic.go
  tests/test_cmd.sh
  tests/topo/full_scale_in_grafana.yaml
Labels: bugfix

#328 cmd: show correctly command name in help messages
  go.mod
  go.sum
  pkg/cliutil/cliutil.go
Labels: bug

#331 task/init: support custom ssh authorized_keys file
  pkg/task/env_init.go
Labels: enhancement

#329 tests: add `check` command to test script
  tests/test_cmd.sh
Labels: testing

#337 Fix using normal binary to run test
  tests/run.sh
Labels: bug, testing

#346 tasks: fix dir creating
  cmd/cluster/command/check.go
  cmd/cluster/command/deploy.go
  cmd/cluster/command/scale_out.go
  cmd/dm/command/deploy.go
  pkg/ansible/dirs.go
  pkg/executor/ssh.go
  pkg/task/builder.go
  pkg/task/chown.go
  pkg/task/context.go
  pkg/task/mkdir.go
  pkg/task/rmdir.go
  pkg/task/ssh.go
Labels: bugfix, enhancement

#355 cmd: fix incorrect data_dir
  cmd/cluster/command/check.go
  cmd/cluster/command/deploy.go
  cmd/cluster/command/reload.go
  cmd/cluster/command/scale_in.go
  cmd/cluster/command/scale_out.go
  cmd/cluster/command/upgrade.go
  cmd/dm/command/deploy.go
  pkg/cliutil/prepare/prepare.go
  pkg/meta/cluster.go
  pkg/meta/logic.go
  pkg/meta/logic_dm.go
  pkg/meta/topology.go
  pkg/meta/topology_test.go
  pkg/operation/check.go
Labels: bug, bugfix
